# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b51a94cc159c4e8d17ce6e5e5bf1eaa2d20b41f1271d3cd920078fd01b0390a993fee6e580c49c9bf91564aed9e8c34f97f72cbd0c8e982313f7fb422139624e

test:
  secret_key_base: 3ef8c462f6c1a25147833a3cabdd913c029962e4ba8f051b7b324f7612b4dfed08b263dfcbcb3265a80e3154c6ffba7b6d08bf6292ce578b7c30b877ac16d148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
